# Generated by Django 3.0.5 on 2021-03-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uppervendor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='uppervendor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Caterer',
        ),
        migrations.DeleteModel(
            name='Decor',
        ),
        migrations.DeleteModel(
            name='Photographer',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.DeleteModel(
            name='UpperVendor',
        ),
    ]
