# Generated by Django 3.0.5 on 2021-03-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0003_caterer_decor_photographer_uppervendor_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uppervendor',
            name='vendor_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
