# Generated by Django 3.0.5 on 2021-03-28 14:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0004_auto_20210328_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='VENUE', max_length=20)),
                ('vendor_opening_time', models.TimeField(default=datetime.time(10, 0))),
                ('vendor_closing_time', models.TimeField(default=datetime.time(23, 0))),
                ('morning_opening_time', models.TimeField(default=datetime.time(10, 0))),
                ('morning_closing_time', models.TimeField(default=datetime.time(16, 0))),
                ('evening_opening_time', models.TimeField(default=datetime.time(17, 0))),
                ('evening_closing_time', models.TimeField(default=datetime.time(23, 0))),
                ('vendor_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VendorApp.UpperVendor')),
            ],
        ),
    ]
