# Generated by Django 3.0.5 on 2021-03-29 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0005_vendortiming'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(default='CATERER', max_length=20)),
                ('vendor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendorApp.UpperVendor')),
            ],
        ),
    ]
