# Generated by Django 3.0.5 on 2021-03-29 19:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0006_vendorimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenuePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_decor', models.IntegerField(default=10000)),
                ('outside_decor', models.BooleanField(default=False)),
                ('venue_halls_ac', models.BooleanField(default=False)),
                ('venue_room_available', models.BooleanField(default=False)),
                ('venue_room_count', models.IntegerField(default=0)),
                ('venue_room_ac', models.IntegerField(default=0)),
                ('room_avg_price', models.IntegerField(default=0)),
                ('room_ac_avg_price', models.IntegerField(default=0)),
                ('changing_room_count', models.IntegerField(default=0)),
                ('changing_room_count_ac', models.IntegerField(default=0)),
                ('advance_percentage', models.IntegerField(default=25, validators=[django.core.validators.MaxValueValidator(100, message='Value cannot be more than 100%')])),
                ('cancellation', models.BooleanField(default=False)),
                ('parking_valet', models.BooleanField(default=False)),
                ('parking_space_count', models.IntegerField(default=10)),
                ('alcohol_allowance', models.BooleanField(default=False)),
                ('outside_alcohol', models.BooleanField(default=False)),
                ('music_allowance', models.BooleanField(default=False)),
                ('late_music_allowance', models.BooleanField(default=False)),
                ('firecrackers', models.BooleanField(default=False)),
                ('overnight_function', models.BooleanField(default=False)),
                ('policy_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VendorApp.UpperVendor')),
            ],
        ),
    ]
