# Generated by Django 3.0.5 on 2021-04-01 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0008_vendorpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuepolicy',
            name='advance_percentage',
            field=models.IntegerField(default=25, validators=[django.core.validators.MaxValueValidator(100, message='Value cannot be more than 100%'), django.core.validators.MinValueValidator(0, message='Value cannot be in negative.')]),
        ),
        migrations.AlterField(
            model_name='venuepolicy',
            name='changing_room_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be in negative.')]),
        ),
        migrations.AlterField(
            model_name='venuepolicy',
            name='changing_room_count_ac',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be in negative.')]),
        ),
        migrations.AlterField(
            model_name='venuepolicy',
            name='parking_space_count',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be in negative.')]),
        ),
        migrations.AlterField(
            model_name='venuepolicy',
            name='room_ac_avg_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be in negative.')]),
        ),
        migrations.AlterField(
            model_name='venuepolicy',
            name='room_avg_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be in negative.')]),
        ),
        migrations.AlterField(
            model_name='venuepolicy',
            name='venue_decor',
            field=models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be in negative.')]),
        ),
        migrations.AlterField(
            model_name='venuepolicy',
            name='venue_room_ac',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be in negative.')]),
        ),
        migrations.AlterField(
            model_name='venuepolicy',
            name='venue_room_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be in negative.')]),
        ),
    ]
