# Generated by Django 3.0.5 on 2021-04-09 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0009_auto_20210401_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='VENUE', max_length=20)),
                ('area_name', models.CharField(max_length=20)),
                ('seating', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
                ('price', models.IntegerField(default=10000)),
                ('venue_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendorApp.UpperVendor')),
            ],
        ),
    ]
