# Generated by Django 3.0.5 on 2021-04-09 18:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0010_partarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='CATERER', max_length=20)),
                ('package_name', models.CharField(max_length=120)),
                ('package_price', models.IntegerField(default=50000)),
                ('max_capacity', models.IntegerField(default=300)),
                ('salads', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('veg_starter', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('veg_main_course', models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('raita', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('dessert', models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('rotis_bread', models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('rice_biryani', models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('dal', models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('welcome_drinks', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('soup', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('non_veg_food', models.BooleanField(default=False)),
                ('non_veg_starter', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('non_veg_main_course', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('vendor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendorApp.UpperVendor')),
            ],
        ),
    ]
