# Generated by Django 3.0.5 on 2021-04-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0011_vendorfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorfood',
            name='non_veg_available',
            field=models.BooleanField(default=False),
        ),
    ]
