# Generated by Django 3.0.5 on 2021-04-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0012_vendorfood_non_veg_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorfood',
            name='non_veg_available',
        ),
    ]
