# Generated by Django 3.0.5 on 2021-04-09 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0013_remove_vendorfood_non_veg_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDecor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='DECOR', max_length=20)),
                ('package_name', models.CharField(max_length=120)),
                ('package_price', models.IntegerField(default=35000)),
                ('max_capacity', models.IntegerField(default=300)),
                ('stage', models.BooleanField(default=True)),
                ('lights', models.BooleanField(default=False)),
                ('flowers', models.BooleanField(default=False)),
                ('furniture', models.BooleanField(default=False)),
                ('entrance', models.BooleanField(default=False)),
                ('lounge', models.BooleanField(default=False)),
                ('vendor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendorApp.UpperVendor')),
            ],
        ),
    ]
