# Generated by Django 3.0.5 on 2021-04-09 23:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0014_vendordecor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPhotographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='DECOR', max_length=20)),
                ('package_name', models.CharField(max_length=120)),
                ('package_price', models.IntegerField(default=25000)),
                ('candid_photo', models.BooleanField(default=False)),
                ('candid_photo_dur', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('candid_person', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('event_photo', models.BooleanField(default=False)),
                ('event_photo_dur', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('event_person', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('videography', models.BooleanField(default=False)),
                ('video_dur', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('video_person', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('main_dur', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7, message='Value cannot be more than 7')])),
                ('vendor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendorApp.UpperVendor')),
            ],
        ),
    ]
