# Generated by Django 3.0.5 on 2021-04-10 14:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VendorApp', '0015_vendorphotographer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.BooleanField(default=False)),
                ('contact_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone No. must be entered in the format +919999999999.', regex='^\\+?1?\\d{9,10}$')])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('confirm_schedule', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendorApp.UpperVendor')),
            ],
        ),
    ]
