# Generated by Django 3.0.5 on 2021-04-12 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VendorApp', '0015_vendorphotographer'),
        ('ClientApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='Corporate', max_length=25)),
                ('event_name', models.CharField(max_length=40)),
                ('venue_require', models.BooleanField(default=True)),
                ('caterer_require', models.BooleanField(default=False)),
                ('decor_require', models.BooleanField(default=False)),
                ('photographer_require', models.BooleanField(default=False)),
                ('deadline', models.DateField()),
                ('min_budget', models.IntegerField(default=35000)),
                ('max_budget', models.IntegerField(default=100000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VenueRequired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientApp.EventPlan')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendorApp.UpperVendor')),
            ],
        ),
        migrations.CreateModel(
            name='PhotographerRequired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientApp.EventPlan')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendorApp.UpperVendor')),
            ],
        ),
        migrations.CreateModel(
            name='DecorRequired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendorApp.UpperVendor')),
                ('event_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientApp.EventPlan')),
            ],
        ),
        migrations.CreateModel(
            name='CatererRequired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendorApp.UpperVendor')),
                ('event_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientApp.EventPlan')),
            ],
        ),
    ]
